Review request
abdellani/project1-Library pull request #1
Opened 2019-09-16 18:02 UTC by abdellani

2019-09-17 10:16 UTC, JamesOkunlade requested changes
### Hello, devs!! 😁 Welcome to the JavaScript section of the curriculum :clap::tada:

Here are my initial observations for this project. I made some comment as well please check them out. They are optional by the way.

- Your code is failing the linter check. Please check the details to see how to fix it. It is important to get a pass on this project and it also makes your code look professional :grin:
- Your `new book` button does not bring up the `new book form`. Please check and fix this. It's advisable to always check your console as well while debugging to pin down where a problem is coming from. 

<img width="1440" alt="Screenshot 2019-09-17 at 11 02 54 AM" src="https://user-images.githubusercontent.com/26285695/65032759-a2415800-d93b-11e9-9e9c-1a2b562c4111.png">

- Your `new book` form should also contain a toggle to indicate whether a book has been read or not.

**Please fix those and request for a re-review.**

**Status**: `Changes required`

**Happy coding!**

2019-09-17 15:38 UTC, EmirVatric commented on javascript/javascript.js
> +  newBook = new Book(title, author, pages);
We have implemented check if all fields are populated on line 24, on button event listener.

2019-09-17 15:51 UTC, abdellani commented
Hi @JamesOkunlade 
Thank you for the review.
The error from sticker says that there is an unexpected token ')'. But we checked our code and we didn't find anything wrong. We also used a character count to check the number of the opening and closing parenthesizes, and we found that they are perfectly balanced. 

![image](https://user-images.githubusercontent.com/16113997/65057689-e1d36880-d96a-11e9-9f11-c2c7bd9d3abc.png)

2019-09-18 07:59 UTC, BalintMendli approved these changes
Hi @abdellani @EmirVatric ,

Nice job, the app works great.

This is a 👍 

You can go ahead and merge the project.

[Optional] Consider adding some styling to the app to make it look nicer.

2019-09-18 14:32 UTC, merged